import './style/index.scss';
import Vue from 'vue';

window.Vue = Vue;
import './components/message';
import {Select, Option} from './components/select';
import Input from './components/input';
import Icon from './components/icon';
import {Flex, FlexItem} from "./components/flex";
import {SplitPanel, SplitPanelItem} from "./components/split-panel";
import {Checkbox, CheckboxGroup} from "./components/checkbox";
import {Radio, RadioGroup} from "./components/radio";
import Slider from './components/slider';
import Button, {Group as BtnGroup} from './components/button';
import $Modal from './components/modal';
import {Table, Column as TableColumn, Pagination} from "./components/table";
import {Form, FormItem} from "./components/form";
import {Row, Col} from "./components/grid";
import {Tab, TabItem} from "./components/tab";
import Portal from './components/portal';
import Spin from './components/spin';
import './components/tooltip';
import LoadingBar from './components/loading-bar'

Vue.component('u-btn', Button);
Vue.component('u-btn-group', BtnGroup);
Vue.component('u-portal', Portal);
Vue.component('u-select', Select);
Vue.component('u-option', Option);
Vue.component('u-input', Input);
Vue.component('u-icon', Icon);
Vue.component('u-flex', Flex);
Vue.component('u-flex-item', FlexItem);
Vue.component('u-split-panel', SplitPanel);
Vue.component('u-split-panel-item', SplitPanelItem);
Vue.component('u-checkbox', Checkbox);
Vue.component('u-checkbox-group', CheckboxGroup);
Vue.component('u-radio', Radio);
Vue.component('u-radio-group', RadioGroup);
Vue.component('u-slider', Slider);
Vue.component('u-modal', $Modal);
Vue.component('u-table', Table);
Vue.component('u-pagination', Pagination);
Vue.component('u-table-column', TableColumn);
Vue.component('u-form', Form);
Vue.component('u-form-item', FormItem);
Vue.component('u-row', Row);
Vue.component('u-col', Col);
Vue.component('u-tab', Tab);
Vue.component('u-spin', Spin);
Vue.component('u-tab-item', TabItem);
Vue.prototype.$LoadingBar = LoadingBar;
export default {};
